task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 80  # COCO classes
remap_mscoco_category: True

model:
  type: DEIM_RTDETRv2
  backbone:
    type: ResNet
    depth: 50
    return_stages: ['res3', 'res4', 'res5']
    out_indices: [1, 2, 3]
    frozen_stages: -1
    norm_eval: False
    pretrained: True
    dcn:
      type: DCNv2
      deform_groups: 1
      fallback_on_stride: False
    stage_with_dcn: [False, True, True]

  neck:
    type: CSPNeXtPAFPN
    in_channels: [512, 1024, 2048]
    out_channels: 256
    num_csp_blocks: 1
    expand_ratio: 0.5
    norm_cfg:
      type: BN
      momentum: 0.1

  query_head:
    type: RTDETRHead
    num_classes: 80
    in_channels: 256
    num_queries: 300

test_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: test_images/
    ann_file: null
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: LoadImage, }
        - {type: Resize, size: [640, 640], }
        - {type: ToTensor, }
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], }
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction 